"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { fireN8nWebhook } from "@/lib/webhooks";

export async function createListing(formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const raw = Object.fromEntries(formData.entries());

  const { data: listing, error } = await supabase
    .from("listings")
    .insert({
      title: raw.title as string,
      type: raw.type as string,
      property_type: raw.property_type as string,
      area: raw.area as string,
      community: (raw.community as string) || null,
      building_name: (raw.building_name as string) || null,
      unit_number: (raw.unit_number as string) || null,
      bedrooms: raw.bedrooms ? Number(raw.bedrooms) : null,
      bathrooms: raw.bathrooms ? Number(raw.bathrooms) : null,
      size_sqft: raw.size_sqft ? Number(raw.size_sqft) : null,
      price: Number(raw.price),
      furnished: (raw.furnished as string) || null,
      parking_spaces: raw.parking_spaces ? Number(raw.parking_spaces) : 0,
      description: (raw.description as string) || null,
      permit_number: (raw.permit_number as string) || null,
      status: (raw.status as string) || "draft",
      assigned_agent_id: (raw.assigned_agent_id as string) || user.id,
      created_by: user.id,
      reference_no: "", // auto-generated by trigger
    })
    .select("id")
    .single();

  if (error) return { error: error.message };

  await supabase.from("activity_logs").insert({
    user_id: user.id,
    action: "listing_created",
    entity_type: "listing",
    entity_id: listing?.id ?? null,
    metadata: { title: raw.title, type: raw.type },
  });

  revalidatePath("/listings");
  redirect("/listings");
}

export async function updateListing(id: string, formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const raw = Object.fromEntries(formData.entries());

  const { error } = await supabase
    .from("listings")
    .update({
      title: raw.title as string,
      type: raw.type as string,
      property_type: raw.property_type as string,
      area: raw.area as string,
      community: (raw.community as string) || null,
      building_name: (raw.building_name as string) || null,
      unit_number: (raw.unit_number as string) || null,
      bedrooms: raw.bedrooms ? Number(raw.bedrooms) : null,
      bathrooms: raw.bathrooms ? Number(raw.bathrooms) : null,
      size_sqft: raw.size_sqft ? Number(raw.size_sqft) : null,
      price: Number(raw.price),
      furnished: (raw.furnished as string) || null,
      parking_spaces: raw.parking_spaces ? Number(raw.parking_spaces) : 0,
      description: (raw.description as string) || null,
      permit_number: (raw.permit_number as string) || null,
      status: (raw.status as string) || "draft",
      assigned_agent_id: (raw.assigned_agent_id as string) || user.id,
    })
    .eq("id", id);

  if (error) return { error: error.message };

  await supabase.from("activity_logs").insert({
    user_id: user.id,
    action: "listing_updated",
    entity_type: "listing",
    entity_id: id,
    metadata: { title: raw.title },
  });

  revalidatePath("/listings");
  redirect("/listings");
}

export async function togglePublish(id: string, publish: boolean) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const { error } = await supabase
    .from("listings")
    .update({ is_published: publish })
    .eq("id", id);

  if (error) return { error: error.message };

  await supabase.from("activity_logs").insert({
    user_id: user.id,
    action: publish ? "listing_published" : "listing_unpublished",
    entity_type: "listing",
    entity_id: id,
  });

  // Fire webhook when publishing
  if (publish) {
    const { data: listing } = await supabase
      .from("listings")
      .select("*")
      .eq("id", id)
      .single();

    const payload = {
      event: "listing.published",
      listing_id: listing?.id,
      listing,
    };

    // Internal logging webhook
    try {
      const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "";
      await fetch(`${baseUrl}/api/webhooks/listing-published`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-webhook-secret": process.env.WEBHOOK_SECRET || "",
        },
        body: JSON.stringify(payload),
      }).catch(() => {});
    } catch {
      // non-blocking
    }

    // n8n automation webhook
    fireN8nWebhook(payload);
  }

  revalidatePath("/listings");
  return { success: true };
}

export async function deleteListing(id: string) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const { error } = await supabase.from("listings").delete().eq("id", id);

  if (error) return { error: error.message };

  await supabase.from("activity_logs").insert({
    user_id: user.id,
    action: "listing_deleted",
    entity_type: "listing",
    entity_id: id,
  });

  revalidatePath("/listings");
  return { success: true };
}
