"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { fireN8nWebhook } from "@/lib/webhooks";

export async function createTransaction(formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const raw = Object.fromEntries(formData.entries());

  // Create transaction
  const { data: txn, error: txnErr } = await supabase
    .from("transactions")
    .insert({
      type: raw.type as string,
      listing_id: (raw.listing_id as string) || null,
      lead_id: null,
      agent_id: raw.agent_id as string,
      deal_value: Number(raw.deal_value),
      commission_amount: Number(raw.commission_amount),
      commission_pct: raw.commission_pct ? Number(raw.commission_pct) : null,
      deal_date: raw.deal_date as string,
      status: "pending",
      notes: (raw.notes as string) || null,
      created_by: user.id,
      reference_no: "", // auto-generated by trigger
    })
    .select("id")
    .single();

  if (txnErr || !txn) return { error: txnErr?.message ?? "Failed to create transaction" };

  // Auto-create commission approval record
  await supabase.from("commission_approvals").insert({
    transaction_id: txn.id,
    agent_id: raw.agent_id as string,
    commission_amount: Number(raw.commission_amount),
    status: "pending",
  });

  // Log activity
  await supabase.from("activity_logs").insert({
    user_id: user.id,
    action: "transaction_created",
    entity_type: "transaction",
    entity_id: txn.id,
    metadata: { type: raw.type, deal_value: Number(raw.deal_value) },
  });

  // Fire webhooks
  const payload = {
    event: "transaction.created",
    transaction_id: txn.id,
    agent_id: raw.agent_id,
    deal_value: Number(raw.deal_value),
  };

  // Internal logging webhook
  try {
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "";
    fetch(`${baseUrl}/api/webhooks/transaction-created`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-webhook-secret": process.env.WEBHOOK_SECRET || "",
      },
      body: JSON.stringify(payload),
    }).catch(() => {});
  } catch {
    // non-blocking
  }

  // n8n automation webhook
  fireN8nWebhook(payload);

  revalidatePath("/transactions");
  redirect("/transactions");
}

export async function updateTransaction(id: string, formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const raw = Object.fromEntries(formData.entries());

  const { error } = await supabase
    .from("transactions")
    .update({
      type: raw.type as string,
      listing_id: raw.listing_id === "none" ? null : (raw.listing_id as string) || null,
      agent_id: raw.agent_id as string,
      deal_value: Number(raw.deal_value),
      commission_amount: Number(raw.commission_amount),
      commission_pct: raw.commission_pct ? Number(raw.commission_pct) : null,
      deal_date: raw.deal_date as string,
      notes: (raw.notes as string) || null,
    })
    .eq("id", id);

  if (error) return { error: error.message };

  await supabase.from("activity_logs").insert({
    user_id: user.id,
    action: "transaction_updated",
    entity_type: "transaction",
    entity_id: id,
    metadata: { type: raw.type, deal_value: Number(raw.deal_value) },
  });

  revalidatePath("/transactions");
  redirect("/transactions");
}
